name: Continuous Integration

on:
  pull_request:
    branches: [main, dev]

jobs:
  # ------------- Front-end ESLint -------------
  lint_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run lint      # assumes you have "lint": "next lint" in package.json

  # ------------- Back-end Black & Flake8 -------------
  lint_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements.txt
          pip install black flake8
      - run: |
          black --check app
          flake8 app

  # ------------- Terraform validate -------------
  terraform_validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: terraform -chdir=terraform init -backend=false
      - run: terraform -chdir=terraform validate